// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: zcrypt.proto

package zcryptpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ZCryptManagerClient is the client API for ZCryptManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZCryptManagerClient interface {
	// RPC method to create the simple device node
	CreateSimpleNode(ctx context.Context, in *CreateSimpleNodeRequest, opts ...grpc.CallOption) (*CreateSimpleNodeResponse, error)
	// RPC method to create a mediated device node
	CreateMdevNode(ctx context.Context, in *CreateMdevNodeRequest, opts ...grpc.CallOption) (*CreateMdevNodeResponse, error)
	// RPC method to fetch active zcrypt nodes
	FetchActiveNodes(ctx context.Context, in *FetchActiveNodesRequest, opts ...grpc.CallOption) (*FetchActiveNodesResponse, error)
	// RPC method to destroy a zcrypt node
	DestroyNode(ctx context.Context, in *DestroyNodeRequest, opts ...grpc.CallOption) (*DestroyNodeResponse, error)
	// RPC method to check if a node exists
	NodeExists(ctx context.Context, in *NodeExistsRequest, opts ...grpc.CallOption) (*NodeExistsResponse, error)
	// RPC method to check if zcrypt has nodes support
	HasNodesSupport(ctx context.Context, in *HasNodesSupportRequest, opts ...grpc.CallOption) (*HasNodesSupportResponse, error)
	// RPC method to create shadow AP sysfs
	MakeShadowApSysfs(ctx context.Context, in *MakeShadowApSysfsRequest, opts ...grpc.CallOption) (*MakeShadowApSysfsResponse, error)
	// RPC method to delete shadow AP sysfs
	DelShadowSysfs(ctx context.Context, in *DelShadowSysfsRequest, opts ...grpc.CallOption) (*DelShadowSysfsResponse, error)
	// RPC method to fetch active shadow sysfs directories
	FetchActiveShadows(ctx context.Context, in *FetchActiveShadowsRequest, opts ...grpc.CallOption) (*FetchActiveShadowsResponse, error)
}

type zCryptManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewZCryptManagerClient(cc grpc.ClientConnInterface) ZCryptManagerClient {
	return &zCryptManagerClient{cc}
}

func (c *zCryptManagerClient) CreateSimpleNode(ctx context.Context, in *CreateSimpleNodeRequest, opts ...grpc.CallOption) (*CreateSimpleNodeResponse, error) {
	out := new(CreateSimpleNodeResponse)
	err := c.cc.Invoke(ctx, "/zcrypt.ZCryptManager/CreateSimpleNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zCryptManagerClient) CreateMdevNode(ctx context.Context, in *CreateMdevNodeRequest, opts ...grpc.CallOption) (*CreateMdevNodeResponse, error) {
	out := new(CreateMdevNodeResponse)
	err := c.cc.Invoke(ctx, "/zcrypt.ZCryptManager/CreateMdevNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zCryptManagerClient) FetchActiveNodes(ctx context.Context, in *FetchActiveNodesRequest, opts ...grpc.CallOption) (*FetchActiveNodesResponse, error) {
	out := new(FetchActiveNodesResponse)
	err := c.cc.Invoke(ctx, "/zcrypt.ZCryptManager/FetchActiveNodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zCryptManagerClient) DestroyNode(ctx context.Context, in *DestroyNodeRequest, opts ...grpc.CallOption) (*DestroyNodeResponse, error) {
	out := new(DestroyNodeResponse)
	err := c.cc.Invoke(ctx, "/zcrypt.ZCryptManager/DestroyNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zCryptManagerClient) NodeExists(ctx context.Context, in *NodeExistsRequest, opts ...grpc.CallOption) (*NodeExistsResponse, error) {
	out := new(NodeExistsResponse)
	err := c.cc.Invoke(ctx, "/zcrypt.ZCryptManager/NodeExists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zCryptManagerClient) HasNodesSupport(ctx context.Context, in *HasNodesSupportRequest, opts ...grpc.CallOption) (*HasNodesSupportResponse, error) {
	out := new(HasNodesSupportResponse)
	err := c.cc.Invoke(ctx, "/zcrypt.ZCryptManager/HasNodesSupport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zCryptManagerClient) MakeShadowApSysfs(ctx context.Context, in *MakeShadowApSysfsRequest, opts ...grpc.CallOption) (*MakeShadowApSysfsResponse, error) {
	out := new(MakeShadowApSysfsResponse)
	err := c.cc.Invoke(ctx, "/zcrypt.ZCryptManager/MakeShadowApSysfs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zCryptManagerClient) DelShadowSysfs(ctx context.Context, in *DelShadowSysfsRequest, opts ...grpc.CallOption) (*DelShadowSysfsResponse, error) {
	out := new(DelShadowSysfsResponse)
	err := c.cc.Invoke(ctx, "/zcrypt.ZCryptManager/DelShadowSysfs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zCryptManagerClient) FetchActiveShadows(ctx context.Context, in *FetchActiveShadowsRequest, opts ...grpc.CallOption) (*FetchActiveShadowsResponse, error) {
	out := new(FetchActiveShadowsResponse)
	err := c.cc.Invoke(ctx, "/zcrypt.ZCryptManager/FetchActiveShadows", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZCryptManagerServer is the server API for ZCryptManager service.
// All implementations must embed UnimplementedZCryptManagerServer
// for forward compatibility
type ZCryptManagerServer interface {
	// RPC method to create the simple device node
	CreateSimpleNode(context.Context, *CreateSimpleNodeRequest) (*CreateSimpleNodeResponse, error)
	// RPC method to create a mediated device node
	CreateMdevNode(context.Context, *CreateMdevNodeRequest) (*CreateMdevNodeResponse, error)
	// RPC method to fetch active zcrypt nodes
	FetchActiveNodes(context.Context, *FetchActiveNodesRequest) (*FetchActiveNodesResponse, error)
	// RPC method to destroy a zcrypt node
	DestroyNode(context.Context, *DestroyNodeRequest) (*DestroyNodeResponse, error)
	// RPC method to check if a node exists
	NodeExists(context.Context, *NodeExistsRequest) (*NodeExistsResponse, error)
	// RPC method to check if zcrypt has nodes support
	HasNodesSupport(context.Context, *HasNodesSupportRequest) (*HasNodesSupportResponse, error)
	// RPC method to create shadow AP sysfs
	MakeShadowApSysfs(context.Context, *MakeShadowApSysfsRequest) (*MakeShadowApSysfsResponse, error)
	// RPC method to delete shadow AP sysfs
	DelShadowSysfs(context.Context, *DelShadowSysfsRequest) (*DelShadowSysfsResponse, error)
	// RPC method to fetch active shadow sysfs directories
	FetchActiveShadows(context.Context, *FetchActiveShadowsRequest) (*FetchActiveShadowsResponse, error)
	mustEmbedUnimplementedZCryptManagerServer()
}

// UnimplementedZCryptManagerServer must be embedded to have forward compatible implementations.
type UnimplementedZCryptManagerServer struct {
}

func (UnimplementedZCryptManagerServer) CreateSimpleNode(context.Context, *CreateSimpleNodeRequest) (*CreateSimpleNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSimpleNode not implemented")
}
func (UnimplementedZCryptManagerServer) CreateMdevNode(context.Context, *CreateMdevNodeRequest) (*CreateMdevNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMdevNode not implemented")
}
func (UnimplementedZCryptManagerServer) FetchActiveNodes(context.Context, *FetchActiveNodesRequest) (*FetchActiveNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchActiveNodes not implemented")
}
func (UnimplementedZCryptManagerServer) DestroyNode(context.Context, *DestroyNodeRequest) (*DestroyNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyNode not implemented")
}
func (UnimplementedZCryptManagerServer) NodeExists(context.Context, *NodeExistsRequest) (*NodeExistsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeExists not implemented")
}
func (UnimplementedZCryptManagerServer) HasNodesSupport(context.Context, *HasNodesSupportRequest) (*HasNodesSupportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HasNodesSupport not implemented")
}
func (UnimplementedZCryptManagerServer) MakeShadowApSysfs(context.Context, *MakeShadowApSysfsRequest) (*MakeShadowApSysfsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeShadowApSysfs not implemented")
}
func (UnimplementedZCryptManagerServer) DelShadowSysfs(context.Context, *DelShadowSysfsRequest) (*DelShadowSysfsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelShadowSysfs not implemented")
}
func (UnimplementedZCryptManagerServer) FetchActiveShadows(context.Context, *FetchActiveShadowsRequest) (*FetchActiveShadowsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchActiveShadows not implemented")
}
func (UnimplementedZCryptManagerServer) mustEmbedUnimplementedZCryptManagerServer() {}

// UnsafeZCryptManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZCryptManagerServer will
// result in compilation errors.
type UnsafeZCryptManagerServer interface {
	mustEmbedUnimplementedZCryptManagerServer()
}

func RegisterZCryptManagerServer(s grpc.ServiceRegistrar, srv ZCryptManagerServer) {
	s.RegisterService(&ZCryptManager_ServiceDesc, srv)
}

func _ZCryptManager_CreateSimpleNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSimpleNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZCryptManagerServer).CreateSimpleNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zcrypt.ZCryptManager/CreateSimpleNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZCryptManagerServer).CreateSimpleNode(ctx, req.(*CreateSimpleNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZCryptManager_CreateMdevNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMdevNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZCryptManagerServer).CreateMdevNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zcrypt.ZCryptManager/CreateMdevNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZCryptManagerServer).CreateMdevNode(ctx, req.(*CreateMdevNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZCryptManager_FetchActiveNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchActiveNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZCryptManagerServer).FetchActiveNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zcrypt.ZCryptManager/FetchActiveNodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZCryptManagerServer).FetchActiveNodes(ctx, req.(*FetchActiveNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZCryptManager_DestroyNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZCryptManagerServer).DestroyNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zcrypt.ZCryptManager/DestroyNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZCryptManagerServer).DestroyNode(ctx, req.(*DestroyNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZCryptManager_NodeExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZCryptManagerServer).NodeExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zcrypt.ZCryptManager/NodeExists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZCryptManagerServer).NodeExists(ctx, req.(*NodeExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZCryptManager_HasNodesSupport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasNodesSupportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZCryptManagerServer).HasNodesSupport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zcrypt.ZCryptManager/HasNodesSupport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZCryptManagerServer).HasNodesSupport(ctx, req.(*HasNodesSupportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZCryptManager_MakeShadowApSysfs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeShadowApSysfsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZCryptManagerServer).MakeShadowApSysfs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zcrypt.ZCryptManager/MakeShadowApSysfs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZCryptManagerServer).MakeShadowApSysfs(ctx, req.(*MakeShadowApSysfsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZCryptManager_DelShadowSysfs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelShadowSysfsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZCryptManagerServer).DelShadowSysfs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zcrypt.ZCryptManager/DelShadowSysfs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZCryptManagerServer).DelShadowSysfs(ctx, req.(*DelShadowSysfsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZCryptManager_FetchActiveShadows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchActiveShadowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZCryptManagerServer).FetchActiveShadows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zcrypt.ZCryptManager/FetchActiveShadows",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZCryptManagerServer).FetchActiveShadows(ctx, req.(*FetchActiveShadowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ZCryptManager_ServiceDesc is the grpc.ServiceDesc for ZCryptManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZCryptManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zcrypt.ZCryptManager",
	HandlerType: (*ZCryptManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSimpleNode",
			Handler:    _ZCryptManager_CreateSimpleNode_Handler,
		},
		{
			MethodName: "CreateMdevNode",
			Handler:    _ZCryptManager_CreateMdevNode_Handler,
		},
		{
			MethodName: "FetchActiveNodes",
			Handler:    _ZCryptManager_FetchActiveNodes_Handler,
		},
		{
			MethodName: "DestroyNode",
			Handler:    _ZCryptManager_DestroyNode_Handler,
		},
		{
			MethodName: "NodeExists",
			Handler:    _ZCryptManager_NodeExists_Handler,
		},
		{
			MethodName: "HasNodesSupport",
			Handler:    _ZCryptManager_HasNodesSupport_Handler,
		},
		{
			MethodName: "MakeShadowApSysfs",
			Handler:    _ZCryptManager_MakeShadowApSysfs_Handler,
		},
		{
			MethodName: "DelShadowSysfs",
			Handler:    _ZCryptManager_DelShadowSysfs_Handler,
		},
		{
			MethodName: "FetchActiveShadows",
			Handler:    _ZCryptManager_FetchActiveShadows_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zcrypt.proto",
}
