// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: zcrypt.proto

package zcryptpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing necessary info for node creation.
// Adapt this based on what zcryptCreateSimpleNode actually needs.
// It likely needs the device path or some identifier.
type CreateSimpleNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodename string `protobuf:"bytes,1,opt,name=nodename,proto3" json:"nodename,omitempty"` // An identifier for the specific zcrypt device
	Adapter  int32  `protobuf:"varint,2,opt,name=adapter,proto3" json:"adapter,omitempty"`  // Maybe the path inside the container (ctrpath from Allocate?)
	Domain   int32  `protobuf:"varint,3,opt,name=domain,proto3" json:"domain,omitempty"`    // Maybe the original host path (devpath from Allocate?)
}

func (x *CreateSimpleNodeRequest) Reset() {
	*x = CreateSimpleNodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zcrypt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSimpleNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSimpleNodeRequest) ProtoMessage() {}

func (x *CreateSimpleNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zcrypt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSimpleNodeRequest.ProtoReflect.Descriptor instead.
func (*CreateSimpleNodeRequest) Descriptor() ([]byte, []int) {
	return file_zcrypt_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSimpleNodeRequest) GetNodename() string {
	if x != nil {
		return x.Nodename
	}
	return ""
}

func (x *CreateSimpleNodeRequest) GetAdapter() int32 {
	if x != nil {
		return x.Adapter
	}
	return 0
}

func (x *CreateSimpleNodeRequest) GetDomain() int32 {
	if x != nil {
		return x.Domain
	}
	return 0
}

// The response message indicating success/failure and potentially the created path.
type CreateSimpleNodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success      bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NodePath     string `protobuf:"bytes,2,opt,name=node_path,json=nodePath,proto3" json:"node_path,omitempty"`             // The path of the created node, if applicable
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Detailed error message if success is false
}

func (x *CreateSimpleNodeResponse) Reset() {
	*x = CreateSimpleNodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zcrypt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSimpleNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSimpleNodeResponse) ProtoMessage() {}

func (x *CreateSimpleNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zcrypt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSimpleNodeResponse.ProtoReflect.Descriptor instead.
func (*CreateSimpleNodeResponse) Descriptor() ([]byte, []int) {
	return file_zcrypt_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSimpleNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateSimpleNodeResponse) GetNodePath() string {
	if x != nil {
		return x.NodePath
	}
	return ""
}

func (x *CreateSimpleNodeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// The request message for creating a mediated device node
type CreateMdevNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Apqn string `protobuf:"bytes,1,opt,name=apqn,proto3" json:"apqn,omitempty"` // The APQN in format "XX.XXXX"
}

func (x *CreateMdevNodeRequest) Reset() {
	*x = CreateMdevNodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zcrypt_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMdevNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMdevNodeRequest) ProtoMessage() {}

func (x *CreateMdevNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zcrypt_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMdevNodeRequest.ProtoReflect.Descriptor instead.
func (*CreateMdevNodeRequest) Descriptor() ([]byte, []int) {
	return file_zcrypt_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMdevNodeRequest) GetApqn() string {
	if x != nil {
		return x.Apqn
	}
	return ""
}

// The response message for mediated device node creation
type CreateMdevNodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success      bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DevicePath   string `protobuf:"bytes,2,opt,name=device_path,json=devicePath,proto3" json:"device_path,omitempty"`       // The path of the created device node (e.g. /dev/vfio/N)
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error message if creation failed
}

func (x *CreateMdevNodeResponse) Reset() {
	*x = CreateMdevNodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zcrypt_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMdevNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMdevNodeResponse) ProtoMessage() {}

func (x *CreateMdevNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zcrypt_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMdevNodeResponse.ProtoReflect.Descriptor instead.
func (*CreateMdevNodeResponse) Descriptor() ([]byte, []int) {
	return file_zcrypt_proto_rawDescGZIP(), []int{3}
}

func (x *CreateMdevNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateMdevNodeResponse) GetDevicePath() string {
	if x != nil {
		return x.DevicePath
	}
	return ""
}

func (x *CreateMdevNodeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// The request message for fetching active nodes
type FetchActiveNodesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FetchActiveNodesRequest) Reset() {
	*x = FetchActiveNodesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zcrypt_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchActiveNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchActiveNodesRequest) ProtoMessage() {}

func (x *FetchActiveNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zcrypt_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchActiveNodesRequest.ProtoReflect.Descriptor instead.
func (*FetchActiveNodesRequest) Descriptor() ([]byte, []int) {
	return file_zcrypt_proto_rawDescGZIP(), []int{4}
}

// The response message containing active nodes
type FetchActiveNodesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes        []string `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`                                   // List of active node names
	ErrorMessage string   `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error message if the operation failed
}

func (x *FetchActiveNodesResponse) Reset() {
	*x = FetchActiveNodesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zcrypt_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchActiveNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchActiveNodesResponse) ProtoMessage() {}

func (x *FetchActiveNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zcrypt_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchActiveNodesResponse.ProtoReflect.Descriptor instead.
func (*FetchActiveNodesResponse) Descriptor() ([]byte, []int) {
	return file_zcrypt_proto_rawDescGZIP(), []int{5}
}

func (x *FetchActiveNodesResponse) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *FetchActiveNodesResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// The request message for destroying a node
type DestroyNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodename string `protobuf:"bytes,1,opt,name=nodename,proto3" json:"nodename,omitempty"` // The name of the node to destroy
}

func (x *DestroyNodeRequest) Reset() {
	*x = DestroyNodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zcrypt_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyNodeRequest) ProtoMessage() {}

func (x *DestroyNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zcrypt_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyNodeRequest.ProtoReflect.Descriptor instead.
func (*DestroyNodeRequest) Descriptor() ([]byte, []int) {
	return file_zcrypt_proto_rawDescGZIP(), []int{6}
}

func (x *DestroyNodeRequest) GetNodename() string {
	if x != nil {
		return x.Nodename
	}
	return ""
}

// The response message for node destruction
type DestroyNodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success      bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                              // Whether the operation was successful
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error message if the operation failed
}

func (x *DestroyNodeResponse) Reset() {
	*x = DestroyNodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zcrypt_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyNodeResponse) ProtoMessage() {}

func (x *DestroyNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zcrypt_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyNodeResponse.ProtoReflect.Descriptor instead.
func (*DestroyNodeResponse) Descriptor() ([]byte, []int) {
	return file_zcrypt_proto_rawDescGZIP(), []int{7}
}

func (x *DestroyNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DestroyNodeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_zcrypt_proto protoreflect.FileDescriptor

var file_zcrypt_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x7a, 0x63, 0x72, 0x79, 0x70, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x7a, 0x63, 0x72, 0x79, 0x70, 0x74, 0x22, 0x67, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x22,
	0x76, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x50, 0x61,
	0x74, 0x68, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2b, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4d, 0x64, 0x65, 0x76, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x61, 0x70, 0x71, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x61, 0x70, 0x71, 0x6e, 0x22, 0x78, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x64,
	0x65, 0x76, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x19,
	0x0a, 0x17, 0x46, 0x65, 0x74, 0x63, 0x68, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x4e, 0x6f, 0x64,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x55, 0x0a, 0x18, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x30, 0x0a, 0x12, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x54, 0x0a, 0x13, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xde, 0x02, 0x0a, 0x0d, 0x5a, 0x43, 0x72,
	0x79, 0x70, 0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x57, 0x0a, 0x10, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x1f,
	0x2e, 0x7a, 0x63, 0x72, 0x79, 0x70, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x69,
	0x6d, 0x70, 0x6c, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x20, 0x2e, 0x7a, 0x63, 0x72, 0x79, 0x70, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53,
	0x69, 0x6d, 0x70, 0x6c, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x64, 0x65,
	0x76, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x1d, 0x2e, 0x7a, 0x63, 0x72, 0x79, 0x70, 0x74, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x64, 0x65, 0x76, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x7a, 0x63, 0x72, 0x79, 0x70, 0x74, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4d, 0x64, 0x65, 0x76, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x10, 0x46, 0x65, 0x74, 0x63, 0x68, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x1f, 0x2e, 0x7a, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x7a, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x48, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x1a,
	0x2e, 0x7a, 0x63, 0x72, 0x79, 0x70, 0x74, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x4e,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x7a, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x7a,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_zcrypt_proto_rawDescOnce sync.Once
	file_zcrypt_proto_rawDescData = file_zcrypt_proto_rawDesc
)

func file_zcrypt_proto_rawDescGZIP() []byte {
	file_zcrypt_proto_rawDescOnce.Do(func() {
		file_zcrypt_proto_rawDescData = protoimpl.X.CompressGZIP(file_zcrypt_proto_rawDescData)
	})
	return file_zcrypt_proto_rawDescData
}

var file_zcrypt_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_zcrypt_proto_goTypes = []interface{}{
	(*CreateSimpleNodeRequest)(nil),  // 0: zcrypt.CreateSimpleNodeRequest
	(*CreateSimpleNodeResponse)(nil), // 1: zcrypt.CreateSimpleNodeResponse
	(*CreateMdevNodeRequest)(nil),    // 2: zcrypt.CreateMdevNodeRequest
	(*CreateMdevNodeResponse)(nil),   // 3: zcrypt.CreateMdevNodeResponse
	(*FetchActiveNodesRequest)(nil),  // 4: zcrypt.FetchActiveNodesRequest
	(*FetchActiveNodesResponse)(nil), // 5: zcrypt.FetchActiveNodesResponse
	(*DestroyNodeRequest)(nil),       // 6: zcrypt.DestroyNodeRequest
	(*DestroyNodeResponse)(nil),      // 7: zcrypt.DestroyNodeResponse
}
var file_zcrypt_proto_depIdxs = []int32{
	0, // 0: zcrypt.ZCryptManager.CreateSimpleNode:input_type -> zcrypt.CreateSimpleNodeRequest
	2, // 1: zcrypt.ZCryptManager.CreateMdevNode:input_type -> zcrypt.CreateMdevNodeRequest
	4, // 2: zcrypt.ZCryptManager.FetchActiveNodes:input_type -> zcrypt.FetchActiveNodesRequest
	6, // 3: zcrypt.ZCryptManager.DestroyNode:input_type -> zcrypt.DestroyNodeRequest
	1, // 4: zcrypt.ZCryptManager.CreateSimpleNode:output_type -> zcrypt.CreateSimpleNodeResponse
	3, // 5: zcrypt.ZCryptManager.CreateMdevNode:output_type -> zcrypt.CreateMdevNodeResponse
	5, // 6: zcrypt.ZCryptManager.FetchActiveNodes:output_type -> zcrypt.FetchActiveNodesResponse
	7, // 7: zcrypt.ZCryptManager.DestroyNode:output_type -> zcrypt.DestroyNodeResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_zcrypt_proto_init() }
func file_zcrypt_proto_init() {
	if File_zcrypt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_zcrypt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSimpleNodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zcrypt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSimpleNodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zcrypt_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMdevNodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zcrypt_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMdevNodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zcrypt_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchActiveNodesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zcrypt_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchActiveNodesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zcrypt_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyNodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zcrypt_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyNodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zcrypt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zcrypt_proto_goTypes,
		DependencyIndexes: file_zcrypt_proto_depIdxs,
		MessageInfos:      file_zcrypt_proto_msgTypes,
	}.Build()
	File_zcrypt_proto = out.File
	file_zcrypt_proto_rawDesc = nil
	file_zcrypt_proto_goTypes = nil
	file_zcrypt_proto_depIdxs = nil
}
