// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: zcrypt.proto

package zcryptpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing necessary info for node creation.
// Adapt this based on what zcryptCreateSimpleNode actually needs.
// It likely needs the device path or some identifier.
type CreateSimpleNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodename string `protobuf:"bytes,1,opt,name=nodename,proto3" json:"nodename,omitempty"` // An identifier for the specific zcrypt device
	Adapter  int32  `protobuf:"varint,2,opt,name=adapter,proto3" json:"adapter,omitempty"`  // Maybe the path inside the container (ctrpath from Allocate?)
	Domain   int32  `protobuf:"varint,3,opt,name=domain,proto3" json:"domain,omitempty"`    // Maybe the original host path (devpath from Allocate?)
}

func (x *CreateSimpleNodeRequest) Reset() {
	*x = CreateSimpleNodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zcrypt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSimpleNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSimpleNodeRequest) ProtoMessage() {}

func (x *CreateSimpleNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zcrypt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSimpleNodeRequest.ProtoReflect.Descriptor instead.
func (*CreateSimpleNodeRequest) Descriptor() ([]byte, []int) {
	return file_zcrypt_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSimpleNodeRequest) GetNodename() string {
	if x != nil {
		return x.Nodename
	}
	return ""
}

func (x *CreateSimpleNodeRequest) GetAdapter() int32 {
	if x != nil {
		return x.Adapter
	}
	return 0
}

func (x *CreateSimpleNodeRequest) GetDomain() int32 {
	if x != nil {
		return x.Domain
	}
	return 0
}

// The response message indicating success/failure and potentially the created path.
type CreateSimpleNodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success      bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NodePath     string `protobuf:"bytes,2,opt,name=node_path,json=nodePath,proto3" json:"node_path,omitempty"`             // The path of the created node, if applicable
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Detailed error message if success is false
}

func (x *CreateSimpleNodeResponse) Reset() {
	*x = CreateSimpleNodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zcrypt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSimpleNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSimpleNodeResponse) ProtoMessage() {}

func (x *CreateSimpleNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zcrypt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSimpleNodeResponse.ProtoReflect.Descriptor instead.
func (*CreateSimpleNodeResponse) Descriptor() ([]byte, []int) {
	return file_zcrypt_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSimpleNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateSimpleNodeResponse) GetNodePath() string {
	if x != nil {
		return x.NodePath
	}
	return ""
}

func (x *CreateSimpleNodeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_zcrypt_proto protoreflect.FileDescriptor

var file_zcrypt_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x7a, 0x63, 0x72, 0x79, 0x70, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x7a, 0x63, 0x72, 0x79, 0x70, 0x74, 0x22, 0x67, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x22,
	0x76, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x50, 0x61,
	0x74, 0x68, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x68, 0x0a, 0x0d, 0x5a, 0x43, 0x72, 0x79, 0x70,
	0x74, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x57, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x1f, 0x2e, 0x7a,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x69, 0x6d, 0x70,
	0x6c, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e,
	0x7a, 0x63, 0x72, 0x79, 0x70, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x69, 0x6d,
	0x70, 0x6c, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x7a, 0x63, 0x72, 0x79, 0x70, 0x74, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_zcrypt_proto_rawDescOnce sync.Once
	file_zcrypt_proto_rawDescData = file_zcrypt_proto_rawDesc
)

func file_zcrypt_proto_rawDescGZIP() []byte {
	file_zcrypt_proto_rawDescOnce.Do(func() {
		file_zcrypt_proto_rawDescData = protoimpl.X.CompressGZIP(file_zcrypt_proto_rawDescData)
	})
	return file_zcrypt_proto_rawDescData
}

var file_zcrypt_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_zcrypt_proto_goTypes = []interface{}{
	(*CreateSimpleNodeRequest)(nil),  // 0: zcrypt.CreateSimpleNodeRequest
	(*CreateSimpleNodeResponse)(nil), // 1: zcrypt.CreateSimpleNodeResponse
}
var file_zcrypt_proto_depIdxs = []int32{
	0, // 0: zcrypt.ZCryptManager.CreateSimpleNode:input_type -> zcrypt.CreateSimpleNodeRequest
	1, // 1: zcrypt.ZCryptManager.CreateSimpleNode:output_type -> zcrypt.CreateSimpleNodeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_zcrypt_proto_init() }
func file_zcrypt_proto_init() {
	if File_zcrypt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_zcrypt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSimpleNodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zcrypt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSimpleNodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zcrypt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zcrypt_proto_goTypes,
		DependencyIndexes: file_zcrypt_proto_depIdxs,
		MessageInfos:      file_zcrypt_proto_msgTypes,
	}.Build()
	File_zcrypt_proto = out.File
	file_zcrypt_proto_rawDesc = nil
	file_zcrypt_proto_goTypes = nil
	file_zcrypt_proto_depIdxs = nil
}
