// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: zcrypt.proto

package zcryptpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ZCryptManagerClient is the client API for ZCryptManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZCryptManagerClient interface {
	// RPC method to create the simple device node
	CreateSimpleNode(ctx context.Context, in *CreateSimpleNodeRequest, opts ...grpc.CallOption) (*CreateSimpleNodeResponse, error)
}

type zCryptManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewZCryptManagerClient(cc grpc.ClientConnInterface) ZCryptManagerClient {
	return &zCryptManagerClient{cc}
}

func (c *zCryptManagerClient) CreateSimpleNode(ctx context.Context, in *CreateSimpleNodeRequest, opts ...grpc.CallOption) (*CreateSimpleNodeResponse, error) {
	out := new(CreateSimpleNodeResponse)
	err := c.cc.Invoke(ctx, "/zcrypt.ZCryptManager/CreateSimpleNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZCryptManagerServer is the server API for ZCryptManager service.
// All implementations must embed UnimplementedZCryptManagerServer
// for forward compatibility
type ZCryptManagerServer interface {
	// RPC method to create the simple device node
	CreateSimpleNode(context.Context, *CreateSimpleNodeRequest) (*CreateSimpleNodeResponse, error)
	mustEmbedUnimplementedZCryptManagerServer()
}

// UnimplementedZCryptManagerServer must be embedded to have forward compatible implementations.
type UnimplementedZCryptManagerServer struct {
}

func (UnimplementedZCryptManagerServer) CreateSimpleNode(context.Context, *CreateSimpleNodeRequest) (*CreateSimpleNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSimpleNode not implemented")
}
func (UnimplementedZCryptManagerServer) mustEmbedUnimplementedZCryptManagerServer() {}

// UnsafeZCryptManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZCryptManagerServer will
// result in compilation errors.
type UnsafeZCryptManagerServer interface {
	mustEmbedUnimplementedZCryptManagerServer()
}

func RegisterZCryptManagerServer(s grpc.ServiceRegistrar, srv ZCryptManagerServer) {
	s.RegisterService(&ZCryptManager_ServiceDesc, srv)
}

func _ZCryptManager_CreateSimpleNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSimpleNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZCryptManagerServer).CreateSimpleNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zcrypt.ZCryptManager/CreateSimpleNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZCryptManagerServer).CreateSimpleNode(ctx, req.(*CreateSimpleNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ZCryptManager_ServiceDesc is the grpc.ServiceDesc for ZCryptManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZCryptManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zcrypt.ZCryptManager",
	HandlerType: (*ZCryptManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSimpleNode",
			Handler:    _ZCryptManager_CreateSimpleNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zcrypt.proto",
}
