apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: my-mutating-webhook
webhooks:
- name: mutatepods.mycompany.com
  clientConfig:
    service:
      name: my-webhook-service
      namespace: customer-1
      path: /mutate
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBVENDQWVtZ0F3SUJBZ0lVR24zSklYRms0KzRhSldMeUhvVjBTbGdhZDJrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0VERU9NQXdHQTFVRUF3d0ZiWGt0WTJFd0hoY05NalF3T0RNd01USXpOVEkzV2hjTk1qVXdPRE13TVRJegpOVEkzV2pBUU1RNHdEQVlEVlFRRERBVnRlUzFqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQU5tVDhIYTJPeWs0MTF6MGk1QXNCWnRQZ2RPVWozcjlVenZFbExnV3lERERQdU1tWGFvV1hsOE0KRThQK2NzYnBKc0I2c2creGZWOU5Kc041WkxGd1F2ckpST1lKTGwyejc4RDBraGFHRHQzRWt0aFNyTFl2OTVxTQpkR0Urb3pDdGdHWWk2cElraWEzcFlkQ2J6dXhXRmJqU3VnS2IzWDlnQzVSWEtkTVFYeE4wWFQwWWorS1g0bzZSCkNTNnZkRkdxWmw0OCs0VkNjSXl5cXNFMkpoWW42Q2ptMnN3RklsdGR3VkxmSVZPTThsc2QrbUEzck5vNVpYVHcKekR6UzRNalVjM3pXTG5JaWMvY1dEcm0xL0t3S1FOYVh1UTd4T1hNUXdpRE9aVW5Mb3VCL21YT2cxdDNzVlZUbgp3QXp4UkI5S1dmc1FlWnBHNzl2Q05NVlRIWnBUNUtVQ0F3RUFBYU5UTUZFd0hRWURWUjBPQkJZRUZBWlhvQmpiClpKZ3VtZC9WS1dnUTZGWW4vTGtlTUI4R0ExVWRJd1FZTUJhQUZBWlhvQmpiWkpndW1kL1ZLV2dRNkZZbi9Ma2UKTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQU0zdm1MS0xncmx0a1Z6bQpaWlE5amF5WkVpM2lUdlJvL2k4WktkbU5IQnhmQ0lsSm83aVdnMWpFa0xGZ0tZMjZIWktjNjZMcmZPTTllSHpoCjhXNU95WVhqSmZUL3c1RzhLWkN3SlBTNHdJaFl5L3REUDdYUGh1WmJXNjNXcTZCQzJFcXI5Y3ptTWhObmZFWC8Kb1IxRGhacjFCMmUxOHNmTUV0SC9SVHBZNzRXR3IrU0s2SUdyakkxcW13SHFSUUNNZFBtVWZobUpNOTNkTGpCdQpXNWg1UmtTeEhoMnRieHd1UngzY25rcHUrbmZrSVpiRHZHME9ITU91TUExeVNTYUpzVm4wSXNsWmx4RTVIZU1uCjhyVXdEeHZPL3hRT08wQkZhOTFFOXY4enVJZ0NlWFF0Vlc3b2E4OEhJRXlQdS9TVVdib29lc2QrR3ZTR1pwRlMKNmVkU3o3bz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 10
