apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cex-prometheus-exporter-sa
  namespace: cex-device-plugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:restricted-v2
subjects:
- kind: ServiceAccount
  name: cex-prometheus-exporter-sa
  namespace: cex-device-plugin
