apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cex-plugin-scc-access
  namespace: cex-device-plugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: cex-plugin-sa
  namespace: cex-device-plugin
