apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cex-plugin-sa
  namespace: cex-device-plugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cex-plugin-role
subjects:
- kind: ServiceAccount
  name: cex-plugin-sa
  namespace: cex-device-plugin
