apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cex-plugin-role
  namespace: cex-device-plugin
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  verbs:
  - get
  - list
  - watch
